
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 20 14:21:26 CLST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR = 8;
  public static final int COMA = 2;
  public static final int EDITAR = 9;
  public static final int POS = 3;
  public static final int ENTERO = 12;
  public static final int COLORES = 14;
  public static final int E_SL = 11;
  public static final int EOF = 0;
  public static final int DIRECCION = 13;
  public static final int PARENTESIS_CERRADO = 7;
  public static final int IGUAL = 5;
  public static final int error = 1;
  public static final int TERMINO = 10;
  public static final int PARENTESIS_ABIERTO = 6;
  public static final int IDENTIFICADOR = 15;
  public static final int DAVALOR = 4;
}

